# PUT YOUR GITHUB ACTION WORKFLOW HERE

name: GitHub Action code check

on: pull_request
  # PUT A TRIGGER HERE
  

jobs:
  tn_job-name: 
    runs-on: ubuntu-latest  
    
    steps:
    - uses: actions/checkout@v4
    - name: checkout files

      run: |
        # PUT A STEP HERE 'uses' or 'run'
        echo "run code quality checks"
